"""add on_delete=cascade for book

Revision ID: 009f33245dc6
Revises: f74d7fe300a7
Create Date: 2024-05-22 22:39:15.724817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009f33245dc6'
down_revision: Union[str, None] = 'f74d7fe300a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
