"""delete cascade for user model

Revision ID: 6efda96d96ad
Revises: e7b3089074d4
Create Date: 2024-05-10 15:32:31.053178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efda96d96ad'
down_revision: Union[str, None] = 'e7b3089074d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_user_id_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'user', ['user_id'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_user_id_fkey', 'book', 'user', ['user_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
