"""delete on_delete=cascade

Revision ID: f74d7fe300a7
Revises: 2cdb88e7fa45
Create Date: 2024-05-22 22:04:14.255425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74d7fe300a7'
down_revision: Union[str, None] = '2cdb88e7fa45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('progress_book_id_fkey', 'progress', type_='foreignkey')
    op.create_foreign_key(None, 'progress', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'progress', type_='foreignkey')
    op.create_foreign_key('progress_book_id_fkey', 'progress', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
